CREATE TABLE IF NOT EXISTS CLIENTS (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
CPF VARCHAR(11)
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(100),
PRICE NUMERIC(20,2)
);

CREATE TABLE IF NOT EXISTS PEDIDO (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   CLIENT_ID INTEGER REFERENCES CLIENTS (ID),
   DATA_PEDIDO TIMESTAMP,
   TOTAL NUMERIC (20, 2),
   STATUS VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS ITEM_PEDIDO (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
   PRODUCTS_ID INTEGER REFERENCES PRODUCTS (ID),
   QUANTIDADE INTEGER
);